### ISSUE TITLE
orjson conversion is faulty

### ISSUE THREAD

**Issue by PawelPeczek-Roboflow** [roboflow/inference#189]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

JSON serialisation introduced in https://github.com/roboflow/inference/pull/166 is faulty when used against requests to `/v1` endpoints that require visualisation - due to presence of field `visualization` with binary content in response

```
Traceback (most recent call last):
  File "/app/inference/core/interfaces/http/http_api.py", line 133, in wrapped_route
    return await route(*args, **kwargs)
  File "/app/inference/core/interfaces/http/http_api.py", line 487, in infer_object_detection
    return await process_inference_request(
  File "/app/inference/core/interfaces/http/http_api.py", line 287, in process_inference_request
    return orjson_response(resp)
  File "/app/inference/core/interfaces/http/http_api.py", line 115, in orjson_response
    return ORJSONResponse(content=content)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
  File "/usr/local/lib/python3.9/site-packages/fastapi/responses.py", line 34, in render
    return orjson.dumps(
TypeError: Type is not JSON serializable: bytes
INFO:     192.168.65.1:19999 - "POST /infer/object_detection HTTP/1.1" 500 Internal Server Error
```

### Minimal Reproducible Example

run HTTP container from main

```python
from inference_sdk import InferenceHTTPClient, InferenceConfiguration, VisualisationResponseFormat

LOCALHOST_CLIENT = InferenceHTTPClient(
    api_url="http://127.0.0.1:9001",
    api_key=API_KEYS["MY_PRIVATE_WORKSPACE_API_KEY"],
)
config = InferenceConfiguration(
    visualize_predictions=True,
)

with LOCALHOST_CLIENT.use_configuration(config):
    r = LOCALHOST_CLIENT.infer(
        DATASET["asl"][0],
        model_id="barbel-detection/2",
    )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by paulguerrie** [comment]
Resolved by https://github.com/roboflow/inference/pull/192
