### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yeldarby** [roboflow/inference#315]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

If you install inside of Docker you need to [ensure you have additional dependencies](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo) otherwise you get an error.

Ideally we should not require these (I think there's a headless version of cv2 we could use). Alternatively maybe we could catch this error and recommend the solve: `apt-get update && apt-get install ffmpeg libsm6 libxext6 -y`

### Environment

```
root@C.10017133:/$ pip freeze | grep inference
inference-cli==0.9.15
inference-gpu==0.9.15
inference-sdk==0.9.15
root@C.10017133:/$ 
```

`pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel` docker with after running `pip install inference-gpu`

<img width="729" alt="image" src="https://github.com/roboflow/inference/assets/870796/7d4cc3cc-9327-46a7-9b1f-33c4034aae9a">

### Minimal Reproducible Example

```
root@C.10017778:~$ inference benchmark python-package-speed -m "yolov8n-640"
Traceback (most recent call last):
  File "/usr/local/bin/inference", line 5, in <module>
    from inference_cli.main import app
  File "/usr/local/lib/python3.10/dist-packages/inference_cli/main.py", line 6, in <module>
    import inference_cli.lib
  File "/usr/local/lib/python3.10/dist-packages/inference_cli/lib/__init__.py", line 8, in <module>
    from inference_cli.lib.container_adapter import (
  File "/usr/local/lib/python3.10/dist-packages/inference_cli/lib/container_adapter.py", line 10, in <module>
    from inference_cli.lib.utils import read_env_file
  File "/usr/local/lib/python3.10/dist-packages/inference_cli/lib/utils.py", line 5, in <module>
    from supervision.utils.file import read_yaml_file
  File "/usr/local/lib/python3.10/dist-packages/supervision/__init__.py", line 9, in <module>
    from supervision.annotators.core import (
  File "/usr/local/lib/python3.10/dist-packages/supervision/annotators/core.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
root@C.10017778:~$ D
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PawelPeczek-Roboflow** [comment]
I've taken a look and not found an elegant solution for the problem. The PR opened by @hvaria suggest switch to headless opencv for CLI completely. The problems are the following:
 * there are installations where we resolve both cli requirements and core lib requirements - in presence of both, without `libGL.so.1` being provided - even if there is no `cv2.imshow(...)` invocation - we have error - which would be the case in @yeldarby example (all libs installed) even with the change
 * CLI uses visualisation (`inference infer` command) - so we cannot completely eliminate standard OpenCV
 
We could probably do the following (tradeoffs, pros and cons that I see outlined)
* have headless as a base requirement and have `[desktop]` extras in all libs and install standard cv on clients wish. Drawbacks:
  * people usually by default would try our lib in GUI-env - and would probably even use `cv.imshow(...)` to visualise, so asking them for additional effort may degenerate developer-experience
* catching the error would be possible - may be not necessarily elegant, but could work. The core of that problem is **not** the fact that one cannot install standard CV without GUI - it's rather the fact of additional shared libs being required - so I am leaning towards that approach, if we cannot apply the next option
* it seems that this problem could be completely avoided - and probably that should be done. If you analyse the series of imports leading to this error - you will discover that in `inference_cli.lib.utils` we import opencv through supervision (btw - it's headless by default and drags this into dependencies we install with `inference`) which is only used there due to `read_yaml_file(...)` util - which can be re-implemented or import could be pushed to another module. In long run - we shall think of developing CLI modules to be more command-oriented - to isolate potential domains of errors

**Comment by hvaria** [comment]
I fully agree with your analysis and the outlined approach to navigate these complexities.

**Comment by diegoeche** [comment]
I tried searching in the issues, but I only found this one. I'm mostly interested in the InferenceHttpClient, and it feels a bit weird to have to install opengl stuff. I just tried updating to 0.47.0, but I still get the same issue.

I'm also using "uv" for the project. Anyway we can use the opencv headless with the inference-sdk?

**Comment by PawelPeczek-Roboflow** [comment]
sdk install `supervision` and we bring opencv there - not sure if I know the solution for headless vs non-headless - this seems to be a global issue

**Comment by cdeil** [comment]
I am using `uv add inference-sdk` and using the `inference_sdk.InferenceHTTPClient` just to run a workflow on Roboflow cloud.
It worked fine locally on MacOS, but then on cloud deployment on Linux Docker I ran into this `ImportError: libGL.so`

I think all the SDK does is stuff you could as well do with PIL and get rid of the OpenCV dependency completely?

1_ What is the workaround to get it to work today?
2_ Can you remove or change the OpenCV dependency to make it better for those of us who just want the `inference_sdk.InferenceHTTPClient`?

<img width="607" alt="Image" src="https://github.com/user-attachments/assets/421b8be3-386b-489d-8626-c28e6933305b" />

**Comment by PawelPeczek-Roboflow** [comment]
hi @cdeil 

1. workaround is to install opencv dependencies in docker 
`RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y`

2. this is a valid idea, yet we have other things on our roadmap - so this change is probably not going to be implemented within next few weeks.

**Comment by PawelPeczek-Roboflow** [comment]
another walk-around would be to create stand-alone script to call endpoint: https://serverless.roboflow.com/docs provides API docs

**Comment by cdeil** [comment]
Thanks for pointing out https://serverless.roboflow.com/docs . Unfortunately I mostly get timeouts, seems the service is very slow, painful to develop and debug against. :-(

With https://detect.roboflow.com I'm usually getting responses within ~ 10 seconds, but I don't see docs for it at https://detect.roboflow.com/docs !?

**Comment by PawelPeczek-Roboflow** [comment]
ok, we have some issues with API for now - exported swagger document for you. Please use this on-line tool to render: https://editor-next.swagger.io/, as the swagger is in version 3.1.0 which some other tools does not support yet

[swagger.json](https://github.com/user-attachments/files/20343534/swagger.json)

**Comment by PawelPeczek-Roboflow** [comment]
we believe the problem with API is related to: https://status.cloud.google.com/incidents/SXRPpPwx2RZ5VHjTwFLx
